### ISSUE TITLE
seethru-convert - The system cannot find the path specified.

### ISSUE THREAD

**Issue by CKarnswaters** [m90/seeThru#17]
I've recently come across this and am using it to accomplish a transparent background for a client of the company I'm working for. But whenever I try to run seethru-convert it simply tells me that The system cannot find the path specified. and drops me off with no other info. Any advice?

**Comment by m90** [comment]
Do you have any further information on this? What's the stack trace your terminal will print? I'd need to know the line where the error actually will be thrown, otherwise this is impossible to debug. Please paste the full error message here.

What's your OS, node version, FFMPEG version, et al.?

**Comment by CKarnswaters** [comment]
I'll provide the information tomorrow morning. I just wanted to let you
know that I got your response and that I will be replying.

**Comment by m90** [comment]
Closing this as inactive. If the issue persists, please open a new one including more information and console output.
