### ISSUE TITLE
seethru.revert: IE error.

### ISSUE THREAD

**Issue by CaioMatias** [m90/seeThru#18]
Hi, I was running some tests with seethru here and got a bug.

"SCRIPT438: Object doesn't support property or method 'remove'"

I'm getting this error when the revert method is called on Internet Explorer 11.

Here are some possible solutions:
http://stackoverflow.com/questions/18919560/object-doesnt-support-property-or-method-remove
http://stackoverflow.com/questions/24934638/html-canvas-object-doesnt-support-property-or-method-remove

I can try to make a pull request when I get a free time.

Great lib btw.
thanks

**Comment by m90** [comment]
Hi, thanks for the bug report.

This must be a problem using `nextSibling` here as you already found out: https://github.com/m90/seeThru/blob/master/src/seeThru.js#L323 - i think the second SO post is spot on.

I'd be happy to accept a PR, but in case you have no time I'll definitely fix that on the weekend.

Thanks!

**Comment by m90** [comment]
@CaioMatias Thanks for your insanely fast fix! 2.1.4 is up and published on npm and bower already.
