### ISSUE TITLE
Canvas tainted by cross-origin data

### ISSUE THREAD

**Issue by darkyan2x** [m90/seeThru#20]
Greetings. I would like to ask if it is possible for seethru to process video which is stored on a different server? For example, I am requesting for seethru to be played on site www.a.com; the source video is located at www.b.com. Is it possible to play the video on site A when the source is on site B? I am finding this on the error of my console:

Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

I think I might have hit a wall this time. I tried using Access-Control-Allow-Origin "*" on my .htaccess file but I still got the same error. I also tried using img.crossOrigin = "Anonymous" but to no avail. I am not sure where the source is at and tried tweaking the code a bit more but still got the same error. Would you happen to know of any workaround to this problem? Thanks.

**Comment by m90** [comment]
Are you sure the CORS-Headers are sent correctly? Have you tried inspecting
the video file in question in your dev tools? Can you see that the correct
headers are present here?

On Wednesday, May 13, 2015, ryan bansi <notifications@github.com> wrote:
> Greetings. I would like to ask if it is possible for seethru to process
video which is stored on a different server? For example, I am requesting
for seethru to be played on site www.a.com; the source video is located at
www.b.com. Is it possible to play the video on site A when the source is on
site B? I am finding this on the error of my console:
>
> Uncaught SecurityError: Failed to execute 'getImageData' on
'CanvasRenderingContext2D': The canvas has been tainted by cross-origin
data.
>
> I think I might have hit a wall this time. I tried using
Access-Control-Allow-Origin "*" on my .htaccess file but I still got the
same error. I also tried using img.crossOrigin = "Anonymous" but to no
avail. I am not sure where the source is at and tried tweaking the code a
bit more but still got the same error. Would you happen to know of any
workaround to this problem? Thanks.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/vdk6lvF9g9raMgOMLVz3AJ9shSuuzvKt2h_9BJ8p10yiieFOP6P_8rej1FDhfSXUWsPaPGbsP_Fr9wgEAd44UFTymZEnE11X4OaCj7QXTYKCzNKZ06IO_xkKneXwNjiHtKiNTw4GD0g4C_sgV50_Rt2sniPZvw=s0-d-e1-ft#https://github.com/notifications/beacon/ABlfFNN4PXrDG5b7lRWaXvHqWsZSDvO7ks5oIpjAgaJpZM4EYk_Y.gif
>

**Comment by jronnyamarante** [comment]
Hi @m90,

I'm working with @darkyan2x on this project and it seems that the video is okay as it is shown on the resources and that the sound plays. 
The only problem is that the rendering on Canvas shows the error message. How can we see if the headers are correct? Should it be the .webm video header or its parent directory?

both the seethru.js and the .webm video are on the same domain -- if it would be of any help.

Thanks a lot.

**Comment by jronnyamarante** [comment]
@m90
We'll also try to do base64 encoding of the video instead as we have tried to flip every stone and found nothing so far. We'll update you. Cheers

**Comment by m90** [comment]
The fact that the video will play does not imply that the correct CORS headers are sent. Is the video publicly available? Could you send me the link in this case?

Also, please be aware that cross domain restrictions want you to host the video on the same host as the HTML document that contains the video. The location of the script does not matter.

**Comment by m90** [comment]
@jronnyamarante In case the video is private could you run the following command against it and post the headers here?

```sh
$ curl -I http://your.server/your-video.webm
```

Example output for the demo file:
```
$ curl -I "http://m90.github.io/seeThru/video/kolor.webm"
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: video/webm
Last-Modified: Mon, 13 Oct 2014 09:45:22 GMT
Access-Control-Allow-Origin: *
Expires: Thu, 14 May 2015 10:03:34 GMT
Cache-Control: max-age=600
Content-Length: 519178
Accept-Ranges: bytes
Date: Thu, 14 May 2015 09:53:34 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-ams4135-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1431597214.082015,VS0,VE268
Vary: Accept-Encoding
```

**Comment by jronnyamarante** [comment]
we have tried doing encoding it as a base64 and it was working. But we think there should be a different and easier way.

============================================================================

Here's the curl result by the way:

HTTP/1.1 200 OK
Date: Tue, 19 May 2015 06:38:17 GMT
Server: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
Last-Modified: Fri, 15 May 2015 10:02:56 GMT
ETag: "57c16a5-d7dc0-5161bf2cc65af"
Accept-Ranges: bytes
Content-Length: 884160
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: x-requested-with, x-requested-by
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: origin, x-requested-with, content-type
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Content-Type: video/webm

**Comment by m90** [comment]
I don't know, but the script works perfectly fine with cross domain video: http://jsfiddle.net/302fooue/

Are you sure you have set up everything correctly?

**Comment by jronnyamarante** [comment]
I have tried this on but it's not working still. :-(
http://jsfiddle.net/d7u2ks6r/

**Comment by m90** [comment]
@jronnyamarante The jsfiddle is an exact clone of the one I posted? Is this supposed to be? What happens when you use your video sources in there?

**Comment by jronnyamarante** [comment]
Yes, I forked your jsfiddle. I just changed the URL of the video file to mine -- the same video file which was cURL'ed

**Comment by jronnyamarante** [comment]
Sorry, wrong link, here's the correct one.
http://jsfiddle.net/d7u2ks6r/1/

**Comment by m90** [comment]
Your video returns `404`:
![bildschirmfoto vom 2015-05-20 13 12 36](https://cloud.githubusercontent.com/assets/1662740/7724470/22963774-fef2-11e4-94ee-f2866182d2b7.png)

**Comment by jronnyamarante** [comment]
@m90 Sorry, forgot to tell @darkyan2x not to delete the files. Here's an updated fiddle.
http://jsfiddle.net/d7u2ks6r/3/

Cheers

**Comment by m90** [comment]
There must be some problem with your server configuration that hinders the video to be played when you add the `crossorigin` attribute to the video tag.

See it playing: http://jsfiddle.net/qh7yamg8/
And failing: http://jsfiddle.net/qh7yamg8/1/

Closing this now as it's not `seeThru` related.
