### ISSUE TITLE
converter not able to generate alpha channel

### ISSUE THREAD

**Issue by meibegger** [m90/seeThru#21]
I exported a test-video from premiere - Quicktime with animation codec and 32bit depth.
I reimported the video to the timeline, and it has an alpha channel.

I also tried different export settings for the frame-rate and field-order, and not to include meta-data ...

But i always get
"An error occurred generating the alpha channel: ffmpeg exited with code 1".

ffprobe output's this info:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'hand_v0_full_progressive_animation.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2015-07-11 13:44:59
  Duration: 00:00:08.71, start: 0.000000, bitrate: 176804 kb/s
    Stream #0:0(eng): Video: qtrle (rle  / 0x20656C72), bgra, 720x480, 175255 kb/s, SAR 109:120 DAR 109:80, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
    Metadata:
      creation_time   : 2015-07-11 13:44:59
      handler_name    : Apple Alias Data Handler
      encoder         : Animation
      timecode        : 00:00:00;00
    Stream #0:1(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2015-07-11 13:44:59
      handler_name    : Apple Alias Data Handler
      timecode        : 00:00:00;00
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2015-07-11 13:45:00
      handler_name    : Apple Alias Data Handler
      timecode        : 00:00:00;00
Unsupported codec with id 0 for input stream 2
```

Do you have any ideas, as to what could be wrong here? Is it this strange stream2? 

Thanks a lot!

**Comment by m90** [comment]
As it states
```
Unsupported codec with id 0 for input stream 2
```
and this seems to be an empty audio track I'd try removing that track at first.

I'm perfectly able to convert progressive animation encoded video on my machine, but there's a lot of factors at play here. What OS are you on? How do you encode the video?

**Comment by meibegger** [comment]
i'm on a mac yosemite. exporting with adobe premiere.
i seem to get this empty stream 2 with any quicktime settings supporting alpha.
even if i run ffmpeg with -map and map the 0:0 and 0:1 channel, then call ffprobe on the result, the 0:2 stream is still there :/ .
but i am not sure, that this is the problem, as i get the same error-message for other files like mp4 witch have no alpha channel.

**Comment by m90** [comment]
To further debug this I'd try the following things:

First of all I'd try doing some really simple operation with ffmpeg on your video, sth like converting your video to mp4:

```sh
ffmpeg -i hand_v0_full_progressive_animation.mov -acodec libfaac -b:a 128k -vcodec mpeg4 -b:v 1200k -flags +aic+mv4 output.mp4
```

If this already fails ffmpeg has a problem with your video that I don't know about. If this succeeds I'd try running the command that `seethru-convert` generates to extract the alpha channel by hand:

```sh
ffmpeg -i hand_v0_full_progressive_animation.mov -vf [in] format=rgba,split [T1], fifo,lutrgb=r=maxval:g=maxval:b=maxval,[T2] overlay [out];[T1] fifo, lutrgb=r=minval:g=minval:b=minval [T2] alpha-output.mov
```

This should tell us if this is an issue with your video, ffmpeg or `seeThru`

**Comment by meibegger** [comment]
I get an "Unknown encoder 'libfaac'", but with -acodec aac and -strict -2, converting to mp4 works.
But when extracting the alpha channel i get this error:
```
[NULL @ 0x7fa4dc80ee00] Unable to find a suitable output format for 'format=rgba,split'
format=rgba,split: Invalid argument
```
I'm using the latest ffmpeg 64bit binary (version 2.7.1).

**Comment by m90** [comment]
Gotta love ffmpeg.

I'm not on a Mac so I have no clue what encoders are available on your machine. Could you try to find out what is available for you and try to convert your video without any further transforms. That way it'd be possible to find out if ffmpeg is able to process your video at all.

**Comment by meibegger** [comment]
So i checked the ffmpeg filter doc https://www.ffmpeg.org/ffmpeg-filters.html and noticed that the filter is in "
Sooooo
```
ffmpeg -i hand_v0_full_progressive_animation.mov -vf "[in] format=rgba,split [T1], fifo,lutrgb=r=maxval:g=maxval:b=maxval,[T2] overlay [out];[T1] fifo, lutrgb=r=minval:g=minval:b=minval [T2]" alpha-output.mov
```
almost works ;)

But as there is no audio codex specified, ffmpeg wats to use AAC, which is experimental and without "-strict -2" the above call fails.

But i think for this step we should use a lossless codec.
I'm not firm with codecs, and therefore not sure, if i used the perfect one, but the following works perfectly fine on my machine:
```
ffmpeg -i hand_v0_full_progressive_animation.mov -vf "[in] format=rgba,split [T1], fifo,lutrgb=r=maxval:g=maxval:b=maxval,[T2] overlay [out];[T1] fifo, lutrgb=r=minval:g=minval:b=minval [T2]" -acodec pcm_s16le alpha-output.mov
```
:)

**Comment by m90** [comment]
> But as there is no audio codex specified, ffmpeg wats to use AAC, which is experimental and without "-strict -2" the above call fails.

Will this also produce the same error as in your initial post?

**Comment by meibegger** [comment]
no. it produces
```
[aac @ 0x7f8d33015400] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```

in any case:
1. the alpha-channel does not need audio - the audio should be in the rgb video
2. the audio should not be compressed anyway

**Comment by meibegger** [comment]
and the problem is not the audio, but first of all the missing " for the filter spec.
at least that is my impression right now ..

**Comment by m90** [comment]
> 1. the alpha-channel does not need audio - the audio should be in the rgb video

That's what I wanted it to do when writing it, but apparently ffmpeg works differently than i thought.

> 2. the audio should not be compressed anyway

This is what's supposed to happen here: https://github.com/m90/seeThru/blob/master/converter.js#L55, but apparently ffmpeg will just "copy" the audio when you don't specify anything like in https://github.com/m90/seeThru/blob/master/converter.js#L55

Two questions:

- would you be able to produce a patch for that?
- in case not, could you somehow send me a snippet of the video so I can do that?

And regarding:
> and the problem is not the audio, but first of all the missing " for the filter spec.
at least that is my impression right now ..

That was just me unable to translate the fluent ffmpeg options to a shell command.

**Comment by meibegger** [comment]
> but apparently ffmpeg will just "copy" the audio when you don't specify anything
I think it doesn't copy it, but tries to use the default codec, which in my case strangely is the experimental AAC - and then fails

to remove the audio from the alpha output: add -an
```
ffmpeg -i hand_v0_full_progressive_animation.mov -vf "[in] format=rgba,split [T1], fifo,lutrgb=r=maxval:g=maxval:b=maxval,[T2] overlay [out];[T1] fifo, lutrgb=r=minval:g=minval:b=minval [T2]" -an alpha-output3.mov
```
works! :)

so probably adding '-an' here https://github.com/m90/seeThru/blob/master/converter.js#L32 could do the trick ... ?

> would you be able to produce a patch for that?
Sorry - i tried, but i don't know how to develop with node ...

> could you somehow send me a snippet of the video
Uploading to Dropbox ... i'll send you the link as soon as it's finished ...

**Comment by meibegger** [comment]
Here is the link to the video ...
https://www.dropbox.com/s/3w525ddeedcd2lr/hand_v0_full_progressive_animation.mov.zip?dl=0

**Comment by m90** [comment]
Thanks for the file. Weird thing is I can perfectly convert your video running a fresh npm install of `2.1.7` on my ubuntu machine running ffmpeg 2.7.1.

Adding the `-an` option makes ffmpeg crash though.

So I gotta look into this a little closer. Thanks for all the input in any case.

**Comment by meibegger** [comment]
hm ... i'm not running an npm-install ... i donwloaded the binaries and just unzipped it to a folder + set the path-variable ... 

does this work for you?
```
ffmpeg -i hand_v0_full_progressive_animation.mov -vf "[in] format=rgba,split [T1], fifo,lutrgb=r=maxval:g=maxval:b=maxval,[T2] overlay [out];[T1] fifo, lutrgb=r=minval:g=minval:b=minval [T2]" alpha-output.mov
```
because for me it produces
```
[aac @ 0x7f8d33015400] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```
which could bet the cause of "crash" on my machine ... 

> Adding the -an option makes ffmpeg crash though.
I just found this https://www.npmjs.com/package/fluent-ffmpeg#audio-options - .noAudio() - maybe you could give it a try?

**Comment by meibegger** [comment]
HURRAYYY!!
seethru-convert --in hand_v0_full_progressive_animation.mov --out test.mov
Processing hand_v0_full_progressive_animation.mov finished!

just add withNoAudio() :)
```
alpha.addOption(
                '-vf'
                , '[in] format=rgba,\
                split [T1], fifo, lutrgb=r=maxval:g=maxval:b=maxval,\
                [T2] overlay [out];\
                [T1] fifo, lutrgb=r=minval:g=minval:b=minval [T2]'
        ).withNoAudio().withVideoCodec(metadata.streams[0].codec_name);
```

**Comment by m90** [comment]
Great! Would you mindestens opening a Pull Request with that fix?

**Comment by meibegger** [comment]
sorry ... do what?
i can go to https://github.com/m90/seeThru/pulls
then "new pull request" takes me to https://github.com/m90/seeThru/compare
and then, no matter what i choose, it says there is nothing to compare ...

**Comment by m90** [comment]
Ok, don't  worry :)

You'd have to fork the repository, commit the changes to your fork and then open a Pull Request against my repo so I could merge your changes and release the fix to npm.

If that's too much of a hassle for you I can apply your fix when I find the time to do so. No worries.

Thanks in any case.

**Comment by meibegger** [comment]
ok - is pushed

**Comment by m90** [comment]
`2.1.8` including your fix is now available on npm: https://www.npmjs.com/package/seethru

Thanks!

**Comment by meibegger** [comment]
great - tested and worked like a charm! thanks!
