### ISSUE TITLE
seethru-convert

### ISSUE THREAD

**Issue by tapouillo** [m90/seeThru#23]
hi,

thanks for this nice tool :)

seethru-convert is always crashing on my centos server, if it can help someone, I managed to create a working video with the following command lines:

// my video source is 325x300, it is causing problems for the overlay, so i scale it first
ffmpeg -y -vprofile high -i original.mov -codec h264 -pix_fmt yuv420p  -s 324x300 ori.mp4

//extract the alpha channel
ffmpeg -y -vprofile high -i original.mov -codec h264 -pix_fmt yuv420p -vf '[in] alphaextract [out]' -s 324x300 alpha.mp4

//mixing the 2 videos
ffmpeg -y -vprofile high -i ori.mp4 -vf '[in] scale=iw:ih, pad=iw:2*ih [top]; movie=alpha.mp4, scale=iw:ih [bottom]; [top][bottom] overlay=0:h [out]' final.mp4

//webm convert
ffmpeg -i input-file.mp4 -c:v libvpx -crf 10 -b:v 1M -c:a libvorbis output-file.webm

another problem: on windows / chrome, the alpha mask is badly rendered, as if it was late on the video, causing a shift. (no problem on osx)

Using webm format fixed the problem, but after a period of time and some video loop, the browser throw a error message: an error occured, memory problem.

**Comment by m90** [comment]
Do you have more information on the error messages that are displayed?

**Comment by tapouillo** [comment]
![capture d ecran 2015-09-22 a 17 02 18](https://cloud.githubusercontent.com/assets/1756753/10022188/d1ac903a-614b-11e5-902a-acbd2d7d8411.png)

nothing relevant:
an error happened while displaying this web page. (...) close applications and tabs to get more memory (...)

**Comment by m90** [comment]
Hard to tell without further information. Does the demo page at http://m90.github.io/seeThru/moving-alpha/ create the same issue with your machine?

**Comment by tapouillo** [comment]
yes, it's crashing too.
while monitoring the processus, i can see that the memory is growing indefinitly. I believe that it will crash faster on small computer with not much memory.
On an old computer, the crash occurs within a minute. 
On a recent mac, still not crashing after 15min, but I see the memory process growing (1GB 5-10 min ago, 2.89MB now )

**Comment by m90** [comment]
When looking at the memory consumption, can you see the garbage collector kicking in at all? Or is the growth linear? I looked at it for five minutes now and see it cycling between 50kb to 250kb using Chrome on Linux.

**Comment by tapouillo** [comment]
![capture d ecran 2015-09-23 a 09 56 47](https://cloud.githubusercontent.com/assets/1756753/10040240/2b555fe8-61da-11e5-8ccd-d8fbce1ea8e4.png)

on the left part of the graph, running with chrome. I stopped it, and ran the same video under firefox, the memory is stable. 

I stopped firefox and ran again the video on chrome, and it starts to grow slowly

**Comment by m90** [comment]
Are you able to debug this as far as taking a memory snapshot in Chrome's dev tools and finding out where the memory leak is happening?

**Comment by tapouillo** [comment]
i'm not seeing a memory leak while taking a snapshot. the heap size stays stable while recording. maybe it's something somewhere else inside chrome, with the memory/video objects management ?

![capture d ecran 2015-09-23 a 12 25 10](https://cloud.githubusercontent.com/assets/1756753/10042806/3950dd0c-61ee-11e5-8597-f9eaaf3e4102.png)

**Comment by tapouillo** [comment]
maybe this can help: https://code.google.com/p/chromium/issues/detail?id=255456

**Comment by m90** [comment]
That's not really what the script is doing though.

There used to be a bug in the first release of Safari 6 that did something similar.

Probably a browser / OS related thing therefore unfortunately.

**Comment by tapouillo** [comment]
yes, maybe it is linked with the getimagedata ...  i tried in the draw frame only to display the video, there is not more memory problems. as soon as there is a getImageData, even without using it, the memory is growing indefinitly

**Comment by m90** [comment]
I think this is the Chromium issue that is causing this: https://code.google.com/p/chromium/issues/detail?id=242215 - closing this now as I probably won't be able to do anything about it.

Thanks!
