### ISSUE TITLE
IE 10 and 11: Unable to get property 'teardown' of undefined or null reference

### ISSUE THREAD

**Issue by slavajacobson** [m90/seeThru#24]
Getting this problem on 2.1.9 and 3.0.0 in IE 10 and 11. Works fine in IE Edge.

Edit:

My bad, I was trying to call revert() on a seeThru object. It appears that the video doesn't get initialized at all and there's no error.

**Comment by m90** [comment]
So is there anything the library can do about that issue or can we close it?

**Comment by slavajacobson** [comment]
My bad. The video's height was over 1200px which is not supported by IE. I thought the plugin was at fault but I was wrong.

Thanks.

**Comment by BriceShatzer** [comment]
@slavajacobson is there documentation somewhere regarding dimension limits? I can't seem to find anything definitive
