### ISSUE TITLE
Video not playing in Chrome

### ISSUE THREAD

**Issue by applesandarrows** [m90/seeThru#26]
I've been working off my local machine and just created a jfiddle. I can get the video to play in firefox, safari, IE, but not in chrome. Please help me! I have noticed since I uploaded it to JFiddle it isn't running the video at all. I assume this has more to do with where I temporarily have the videos hosted that I'm linking to. This won't be the case with the end result. First, I need to figure out why my video won't play in Chrome. 

Please take a look. Any help you can give I would appreciate.

https://jsfiddle.net/mjbomar/jf4c9h82/

**Comment by m90** [comment]
When downloading the files and setting things up in a way that we are not bitten by [CrossDomain issues](https://github.com/m90/seeThru#cross-domain-issues-with-canvas-elements) your video works just as expected in all browsers including Chrome: http://www.frederikring.com/tmp/ 

To further debug your issue please try to create a minimal setup that does nothing but apply seeThru to your video.

A minimal setup looks like:

```html
<script src="https://unpkg.com/seethru@3.0.1/dist/seeThru.min.js"></script>
<video autoplay id="movingAlphaVid" style="display: none;" preload="auto" />">
  <source src="/video/video_test_combined.mp4#t=0,2.5" type='video/mp4; codecs="avc1.42E01E"' />
  <source src="/video/video_test_combined.webm#t=0,2.5" type='video/webm; codecs="vorbis,vp8"' />
  <source src="/video/video_test_combined.ogg#t=0,2.5" type='video/ogg; codecs="theora, vorbis"' />
</video>
<script>
  seeThru.create('#movingAlphaVid', {
    width: 400,
    height: 300
  });
</script>
```
If you encounter errors please check your console and also check the headers your server sends along when delivering the video files. You might want to compare them with the ones that are used in the working example and check for differences.

**Comment by applesandarrows** [comment]
Thank you for your help! I was able to get it working http://mjbomar.co.nf/index.html. I added my css and other things in one at a time and its working.

Now does this mean I can reuse this code over and over. Just changing out the links? Without cross browser issues?

I would like to ask if you know if there is a way to get rid of the opaque/off white background behind the video in chrome? I have not background set in css. In Firefox and Safari that off white background isn't there it looks completely transparent.

Also, I added a poster image with a bit of php so that when the page loads it will show the poster image. But, the image is randomized. However, my poster image doesn't show up before the video at all. I'd like the poster image to stay visible for 4 seconds before playing the video.

I know these two things might be outside of your wheel house but any help you can give me I'd be grateful.

**Comment by m90** [comment]
Good to see that it worked for you now.

Regarding your two issues:

- the off white background is probably due to this: https://github.com/m90/seeThru#chrome-and-m4v-issues
- there is a dedicated option for handling poster frames: https://github.com/m90/seeThru#options - you can use that and handle the 4 seconds in your client side script
