### ISSUE TITLE
Loop - set loop point rather than loop entire video?

### ISSUE THREAD

**Issue by joeshock** [m90/seeThru#27]
Hello!

First off, thank you for this amazing script! It's been a miracle worker for our lovely state of lack of alpha in HTML5 video cross-browser.

Second, do you have an idea how I could play a video and then instead of looping back to the beginning, loop back to let's say the 2 second mark of the video? Kind of like a gotoAndPlay() operation from the old school Flash days?

**Comment by m90** [comment]
So you do not necessarily need to use seeThru to control the video. If you define the event handling on the video element itself, the canvas representation will be updated accordingly. A little something like:

```js
seeThru
    .create('#your-video')
    .ready(function(instance, video) {
        video.addEventListener('ended', function() {
            video.currentTime = 1234; // whatever works
        });
    });
```

**Comment by joeshock** [comment]
Awesome! I'll give it a try!

**Comment by joeshock** [comment]
Worked great! Thanks again.
