### ISSUE TITLE
Canvas output appears "choppy"

### ISSUE THREAD

**Issue by dtab428** [m90/seeThru#28]
Hello,

I'm utilizing seeThru for a project - see sample here: http://playground.cmlmediasoft.com/Transparent-Video/transvideo.html

It works perfectly; however, the output is slightly laggy. The video source file is very smooth. Anything I can do to remedy this?

**Comment by m90** [comment]
Well, that's quite some heavy lifting the browser needs to do when you display HD video, so I am not really surprised performance is degraded. I do not really think there is a "fix" for that, but if you are really looking into optimizing this I'd either change the dimensions of the video or try adjusting the frame rate you are using to decrease browser computation load.
