### ISSUE TITLE
Poster not visible.

### ISSUE THREAD

**Issue by zabellfour** [m90/seeThru#37]
Option poster: true  is not working. Postes is not shown.

**Comment by m90** [comment]
I can confirm that it stopped working in Chrome, but it still works in other browsers for me. Can you confirm that behavior?

**Comment by zabellfour** [comment]
No, it doesnt work for example in FireFox in Edge. The elemet ".seeThru-poster"  exist at DOM, but it is blank no image or backgrounf,  see screenshot http://joxi.ru/DmBZy3ztNgBkDm.

**Comment by m90** [comment]
I guess it's happening here: https://github.com/m90/seeThru/blob/69753eacabd2da8ca9506d540edc97dba7fcf393/src/seeThru.js#L399-L408 and the camel cased keys are now being skipped for whatever reason. If you want to fix this feel free to open a PR.

**Comment by m90** [comment]
Resolved by #38
