### ISSUE TITLE
iOS 10 - new status

### ISSUE THREAD

**Issue by jakob-e** [m90/seeThru#39]
As of iOS 10 videos are allowed to play inline (_works with _seeThru__) if:
- video has attribute " playsinline" and
- video has no audio track or
- video has attribute "muted"
````HTML
<video id="vido" autoplay loop playsinline muted></video>
````
Ref: [https://webkit.org/blog/6784/new-video-policies-for-ios](https://webkit.org/blog/6784/new-video-policies-for-ios)
Test: [https://codepen.io/jakob-e/pen/RZypBp/](https://codepen.io/jakob-e/pen/RZypBp/)

**Comment by m90** [comment]
Closed via https://github.com/m90/seeThru/commit/c81897d75a7b61afd9d7521adc0a1c1e011d163e - thanks for the additional info.

**Comment by adamwright32** [comment]
This doesn't work for me and the codepen example doesn't play either when i view on browserstack.

I'm doing it the same as on here http://mjbomar.co.nf/index.html, works perfect in all apart from ios and android on browserstack. Any ideas? Known issue? is it cause even though we have auto play the seeThru script is initialising the play?
