### ISSUE TITLE
I allways get visible rectangle

### ISSUE THREAD

**Issue by thecosss** [m90/seeThru#43]
This is not umult
![no-unmult](https://user-images.githubusercontent.com/4847308/29574112-eb2a9f42-8760-11e7-9608-d7429dca17a9.jpg)

Thus is unmult
![umult](https://user-images.githubusercontent.com/4847308/29574120-ee779984-8760-11e7-8b9e-75dbe9b9a679.jpg)

This AE settings
![rgb-straight](https://user-images.githubusercontent.com/4847308/29574606-5c6d18fa-8762-11e7-96bf-7c3d441a4b8d.jpg)
What should i do to get rid of this opacity rectangle?

**Comment by m90** [comment]
Is this Chrome only by any chance, it looks a lot like: https://github.com/m90/seeThru/wiki/FAQs#im-seeing-a-slight-foggy-background-behind-all-videos-in-chrome

Also see: https://github.com/m90/seeThru/issues/12

**Comment by thecosss** [comment]
Thanks, it was a converter issue, the black was #101010 in hex, now everything is fine!
