### ISSUE TITLE
How to change size of the rendered canvas after window resize?

### ISSUE THREAD

**Issue by thecosss** [m90/seeThru#44]
I'm not a programmer. I tried to revert an instance and than do .create() but it doesn't work

**Comment by m90** [comment]
It should theoretically be possible to do that only with CSS (i.e.no need for additional scripting), but that is heavily dependent on the context in which you are using seeThru. Could you create an example JSFiddle or ESBin (or whatever you prefer) that demonstrates your use case?

**Comment by thecosss** [comment]
Actually i already solved this. Revert and then .create() actually worked.
