### ISSUE TITLE
IOS 10

### ISSUE THREAD

**Issue by adamwright32** [m90/seeThru#48]
This doesn't work for me https://github.com/m90/seeThru/issues/39 and the codepen example doesn't play either when i view on browserstack.

I'm doing it the same as on here http://mjbomar.co.nf/index.html, works perfect in all apart from ios and android on browserstack. Any ideas? Known issue? is it cause even though we have auto play the seeThru script is initialising the play?

ok looks like the issue is cause the video is hidden using display: none. I've done a super untested hack on this to force display block using important and then setting the width:0; height:0;

**Comment by m90** [comment]
So is that an issue with the library or in your code? Is this still relevant?

**Comment by adamwright32** [comment]
I'd say with the library as you are hiding the original video 

`"video.style.display = 'none'; line 413`

This seems to prevent the video from playing with the new ios settings 

`<video id="video" autoplay loop playsinline muted></video>`

I've got round this by doing the following css to keep the video visible to the browser. i've tested this across browserstack ie11+, chrome, ff, ios iphone, android devices. works like a charm but you might have a better solution. Think this would be a great feature to add.

```
#video {
	display: block !important;
	height: 0;
	position: absolute;
	width: 0;
	z-index: -10;
}
```

**Comment by m90** [comment]
I need to check if the proposed solution generates any unwanted sideeffects in any other setup once I do have access to sth like Browserstack (I don't have actual devices to repro that atm). I'll let you know what I find out.

In the meantime feel free to open a PR against this repo that uses the approach you are describing. Ideally we'd even have something that enables multiple ways of hiding the video (I'd be afraid of the CSS becoming too specific for a library usecase soon). Maybe it'd be a thing to pass in an optional function as an option that will be passed the element and then can do "custom hiding" like in the case you describe.

**Comment by m90** [comment]
@adamwright32 I had a quick go at what I just described in this branch: https://github.com/m90/seeThru/tree/cdfa1734743ae946a1b775c4ceaffdecee9728b1

which would basically let you override the setting of `display: none` by passing in a hash-version of your desired styles if you need it.

Could you check if that works for you and fits your needs?

I'm kind of reluctant of changing the defaults while this is still version 3, but I guess it'd be a good idea to thoroughly research if your proposal is a better fit once this will become a v4.

**Comment by m90** [comment]
I'm closing this via [v3.2.1](https://github.com/m90/seeThru/releases/tag/3.2.1) which is enabling the user to pass in custom CSS that is used for hiding the video while being see thru.
