### ISSUE TITLE
Can I use this in React?

### ISSUE THREAD

**Issue by pizza0502** [m90/seeThru#51]
Hi, want to ask can I use seeThru in React?
Any example showing how can this works in React?

**Comment by m90** [comment]
I'm pretty sure you can use seeThru with React although I have never done it myself (but I remember issues like #45 talking about it).

You would probably need to call `create` in `componentDidMount` (at least that's what it was called the last time I used React, which is a while back) and then make sure the rendering does not affect the canvas element that is being created when it's not wanted.

**Comment by m90** [comment]
Closing this as inactive. If you have further questions, feel free to reopen.
