### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kuka** [m90/seeThru#6]
hello again. now i am having an issue with memory leak. 3 videos go up to ~1.6gb.. then, i found out that demo of this triangle illuminati cartoon is 1gb too in chrome task manager.. had not figured out anything yet.. 

would really appreciate any help! thanks!

**Comment by slavajacobson** [comment]
I am getting this problem on some computers running Chrome. Memory usage keeps raising till about 2GB and then the tab would crash.

Yet on Ubuntu, the Tab gets to around 3GB and then drops down to 300mb, and it keeps on looping.

**Comment by slavajacobson** [comment]
So in order to prevent crashing, I resized the videos down to 350x674, as a result the tab keeps looping between 230mb to 500mb RAM, it takes about 3-4 seconds to raise from 230mb to 500mb, and it will continue doing it over and over while the Tab is active.

While on Windows machines it will loop between 200mbs and 900mbs.

What's interesting though, there's one windows machine where the tab stays at 50mb.

**Comment by m90** [comment]
@slavajacobson Could you try to find out if you can reproduce the same behavior when solely drawing a video onto a canvas element? I am still not sure if all these memory leak issues derive from something that unique to seeThru, but will stem from the very basic mechanism and how browsers implement this.

**Comment by tysonyau** [comment]
I was able to reproduce the memory leak in chrome when a large video is being used. It appears that the `drawFrame` function is being looped even after the video ends. To combat this, I ran the `stopRendering` function on end. This doesn't solve this issue, it just stops seeThru from chew more memory.

`
seeThru.create('#video', {
    end: 'stop',
    width: 1200,
    height: 675
}).ready(function(instance, video, canvas) {
    video.addEventListener('ended', function(){
        instance._seeThru.stopRendering();
    });
});
`

**Comment by m90** [comment]
@tysonyau Thanks for finding that out. I will try to look into it as soon as I find the time. In the meantime feel free to fork away.

**Comment by m90** [comment]
Hey @tysonyau I finally found the time to look into this issue. Since I am still unable to reproduce it in any way, could you check if the code on [this branch](https://github.com/m90/seeThru/tree/memory-leak) fixes the issue for you? Thanks for your patience!

**Comment by m90** [comment]
@tysonyau Did you ever get the chance to test this?

**Comment by tysonyau** [comment]
@m90, this prevents seeThru from consuming more memory when the video ends. Please keep in mind that this doesn't help videos that loop.

**Comment by m90** [comment]
@tysonyau But how would I be able to flush the consumed memory once the video starts all over again?
