### ISSUE TITLE
final result is black

### ISSUE THREAD

**Issue by lv2lrn4lf** [m90/seeThru#79]
in your example the color is maintain in the final result video. I lose the color and everything get turn into black shapes on a transparent background. 

i made the file to do the pull request but I think you block pull request cause it said cannot do pull request unless I did it already or you have to accept it or idk. but I fork it and made the file yo can see it in script...

Just tell me what to do, and I'll do it.

**Comment by lv2lrn4lf** [comment]
the issue is I don't have a source. I'm generating a video o the fly and need to convert the black background to transparent. How to modify the script to remove all black since all background will have a black background color by the time it reaches this point.

**Comment by m90** [comment]
Pull requests are enabled for this repository, so you should definitely be able to create one https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

About the issue you describe, I can't really advise on how to solve it as if you provide a black RBG frame and an alpha layer, the script will of course render a black shape. If your video turns black and you want it to become transparent, this will need to be reflected in the alpha layer as well.

**Comment by lv2lrn4lf** [comment]
Okay i did it, had to do some research I'm use to using git in bash but not git on github. I had to do the pull from my repo not your repo that where I was confuse at.

So you telling me, that it can perfectly remove the color and background but it has to turn the image black?

I realize that you use two video when doing this effect, like you said, one being color and the other being black and white for alpha detecting. So if you don't have that, it'll do the removing of the black background but turn the image on the front ground black.

And I might be describing it wrong. again, I have a live video feed with let say a red apple floating on it and a black background, when I 

```
var transparentVideo = seeThru.create('#my-video');
```

on a video that don't provide a black and white version for alpha conversion will remove the black background but also turn the image black. 

You have any ideal on what to do to keep the color without providing a black and white version of the video cause again this is like a live feed or a video made on the fly while it being viewed.
